# Generated by Django 5.0.4 on 2024-04-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryMgtSys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='ABC', max_length=255),
            preserve_default=False,
        ),
    ]
